### PR TITLE
don't require tokio rt-multi-thread feature

### PR DESCRIPTION
**Pull request by lunixbochs**

### CODE REVIEW

**Comment by DataTriny** [comment]
Hello @lunixbochs 
Please run `cargo fmt` on your branch.

**Comment by lunixbochs** [comment]
done

**Comment by mwcampbell** [comment]
How exactly does this work? Why is it necessary to spawn a new thread, create a tokio runtime on that thread, send the runtime back, and then exit the thread that created it?

**Comment by lunixbochs** [comment]
Wow, I think I was completely on autopilot. I'd only done basic compile+println testing because existing versions of Accerciser still don't work with Accesskit on Linux due to #241

Sending a handle back and parking the thread on a sleep works much better. I tested this approach further by manually connecting to the bus and verified some atspi methods work.

**Comment by mwcampbell** [comment]
This approach looks good to me. I just belatedly approved the CI workflow.

**Comment by DataTriny** [comment]
The winit example seem to still work properly with the `tokio` feature on.

**Comment by lunixbochs** [comment]
I just realized I can send the runtime into the thread on creation, which simplifies the code quite a bit.

**Pull request merged**
