### PR TITLE
Update license field following SPDX 2.1 license expression standard

### PR DESCRIPTION
**Pull request by frisoft**
The new recommendation is to follow the SPDX 2.1 standard. This allows automatic license verification software to work properly. Reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

### CODE REVIEW

**Review by DataTriny — APPROVED** [review]
This was on my todo list, thank you!

**Comment by waywardmonkeys** [comment]
@frisoft If you could rebase this stop current `main`, that would be great and would fix the failing CI check.

**Comment by frisoft** [comment]
Sure. I'll revise it

**Comment by frisoft** [comment]
@waywardmonkeys, I merged your main into mine. This should be enough to fix the PR.

**Review by waywardmonkeys — APPROVED** [review]

**Pull request merged**
