### PR TITLE
feat: Support the enumn crate in all public enums

### PR DESCRIPTION
**Pull request by mwcampbell**
I think I need this for my JNI bindings.

### CODE REVIEW

**Comment by DataTriny** [comment]
@mwcampbell You forgot to include the changes to `Cargo.toml` and `Cargo.lock`.

**Comment by mwcampbell** [comment]
It turns out that no such changes are needed, because the accesskit crate already has an optional dependency on enumn (and therefore, an enumn feature); that dependency/feature was needed for our serialization implementation.

**Review by DataTriny — APPROVED** [review]

**Comment by DataTriny** [comment]
Indeed you're right, I missed that.

**Comment by mwcampbell** [comment]
Merged as a fix rather than a feature because it's not a breaking change, and I don't want to bump semver-major version numbers for something this small.

**Pull request merged**
