### PR TITLE
Fix doc build for accesskit_winit

### PR DESCRIPTION
**Pull request by dhardy**
Should fix doc build for https://docs.rs/crate/accesskit_winit/

### CODE REVIEW

**Comment by mwcampbell** [comment]
@dhardy Please back out the change to accesskit_c. I don't want to trigger a new release of that crate with the changelog entry from this PR.

**Comment by dhardy** [comment]
@mwcampbell the reason for that is a reported conflict of name when building `cargo doc --all` (or similar). But that probably isn't necessary for this exact issue, so will do.

**Comment by DataTriny** [comment]
Yeah I noticed it too... It won't be an issue with docs.rs since this crate is never published, but we will have to fix it.

**Comment by mwcampbell** [comment]
@dhardy Please do open a separate PR with the accesskit_c fix. Thanks.

**Pull request merged**
