### PR TITLE
Add `is_root` method to `accesskit_consumer::Node`

### PR DESCRIPTION
**Pull request by mwcampbell**

### CODE REVIEW

**Comment by mwcampbell** [comment]
@DataTriny Can you please review this? This change is really simple, but I want to get into the habit of having all code changes reviewed.

**Comment by DataTriny** [comment]
Looks OK to me. Maybe in the future you could add a test ensuring its behavior with a detached node.

I don't have the right to approve your PR though.

**Comment by mwcampbell** [comment]
I don't know how to create a scenario with a detached non-root node in the current tree implementation. So I just added a basic test.

**Comment by DataTriny** [comment]
I'm fine with your test. I didn't expect you to test the detached behavior right now anyway.

**Pull request merged**
