### PR TITLE
fix: Update `windows` to `0.54`

### PR DESCRIPTION
**Pull request by DataTriny**
The major highlight of this PR is that `VariantFactory` is replaced by a simpler `Variant` newtype. The `VARIANT` type from the `windows` crate is used directly whenever possible.

### CODE REVIEW

**Comment by mwcampbell** [comment]
@DataTriny Are you sure that calling `HRESULT::from_win32` on `UIA_E_ELEMENTNOTAVAILABLE` and `UIA_E_INVALIDOPERATION` is correct? Those constants are already `HRESULT` codes, not Win32 errors. I guess we need tests that cover those errors.

**Comment by mwcampbell** [comment]
I think what we need to do is just directly construct the `HRESULT` struct, like this:

```
HRESULT(UIA_E_ELEMENTNOTAVAILABLE as _)
```

This is based on looking at how constants like `windows::Win32::Foundation::E_NOTIMPL` are written.

**Comment by DataTriny** [comment]
@mwcampbell I tried printing a debug representation of those errors and I think you're right.

**Comment by DataTriny** [comment]
I previously made sure that `Error::empty()` was equivalent to `Error::OK`.

**Pull request merged**
