### PR TITLE
fix: Update atspi dependency

### PR DESCRIPTION
**Pull request by mwcampbell**
@DataTriny Please make sure this doesn't break anything in the Unix adapter. If not, let's get this out quickly.

### CODE REVIEW

**Review by DataTriny — APPROVED** [review]
The winit example still runs fine! Doesn't seem to be a win in terms of dependency count though...

**Comment by mwcampbell** [comment]
I caught the extra dependencies (a bit late) and reported the issue. Tait turned around a fix quickly. Please check again; should be a win now.

**Comment by DataTriny** [comment]
@mwcampbell I know about the two extra deps, I was planning on submitting a PR today but you were quicker. The winit example used to report 200 dependencies and now it's at 201. I don't think we should take the time to investigate this now so let's land this and deal with the dependency issue later. At least binary size decreased and fore me this is the most important.

**Comment by DataTriny** [comment]
Oh maybe I wasn't clear here. Indeed the dependency count dropped by bumping to latest `atspi`. But the count seems to have roughly stayed the same between the time I tried yesterday with latest `main` (before your PR) and today.

**Pull request merged**
