### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by DataTriny**
Inspired by druid repository's GitHub actions setup.

Adds a GitHub actions pipeline that will run on every commits to `main` and all pull requests.

It contain two jobs:

- a `cargo fmt` on the whole workspace,
- a `cargo clippy` and `cargo test` that will also run on the entire workspace but on Ubuntu, MacOS and Windows 10 environments.

I also added a badge displaying the status of this pipeline in the README to bring credibility in the project.

Hopefully I got it right because I couldn't find a simple way to "dry run" it.

### CODE REVIEW

**Comment by mwcampbell** [comment]
It looks like the CI badge in the README is just an image, not a full link.

Also, can you do a dry run in your own fork of the repo, on your own main branch?

**Comment by DataTriny** [comment]
You're right about the badge, I fixed it.

However with the current configuration of clippy, the job fail due to two errors. You can consult the reports [here](https://github.com/DataTriny/accesskit/actions/runs/1148837248).

Let me know if this sounds OK to you. But don't merge yet, I'll have to revert some URLs.

**Comment by mwcampbell** [comment]
I just pushed a fix for the clippy warning. Looks like that warning was recently added to clippy; I had to update my local toolchain to get it.

**Comment by DataTriny** [comment]
Merging your fix into my `main`, [everything is green](https://github.com/DataTriny/accesskit/actions/runs/1149930256).

Do we need something else for now?

**Pull request merged**
